### PR TITLE
breaking: refactor AuthContextProvider interfaces, remove token

### PR DESCRIPTION
**Pull request by darahayes**
### Description

For verification, if you link up these changes into the showcase app, you should be able to follow the same steps provided here: https://github.com/aerogear/ionic-showcase/pull/228

And ideally you shouldn't see any issues.

##### Checklist

- [x] `npm test` passes
- [x] `npm run build` works
- [x] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
I would like to extend exsisting unit test or integrationm test with auth context provider so we can kinda fail if things go bad. 

With current form this is more like header provider than auth context provider as it is not auth specific. People can still drop their link to apply any custom headers so we are ok.

**Comment by wtrocki** [comment]
I would like to extend the exsisting unit test or integration test with the auth context provider so we can kinda fail if things go bad. 

With current form, this is more like header provider than auth context provider as it is not auth specific. People can still drop their link to apply any custom headers so we are ok.

**Comment by darahayes** [comment]
> With current form, this is more like header provider than auth context provider as it is not auth specific. People can still drop their link to apply any custom headers so we are ok.

I totally agree. It makes things more flexible but still allows us to provide what we need in terms of keycloak -> sync integration

**Comment by wtrocki** [comment]
@darahayes Can you also add info to RELEASE_NOTES.md

**Comment by darahayes** [comment]
PR for release notes: https://github.com/aerogear/aerogear-js-sdk/pull/412

**Pull request merged**
