### PR TITLE
AEROGEAR-8027 - send client info when audit logging enabled

### PR DESCRIPTION
**Pull request by aliok**
With this PR, GraphQL requests now have the client info (client id, app info, device info) in the extensions part of a request. That's only done when auditLogging is enabled.
The code that's collecting the client info is made reusable.

### Verification instructions:

*NOTE*: Device/app/client info can't be collected in the browser. You need to verify using Cordova.

#### 1. Voyager server

Get https://github.com/aerogear/apollo-voyager-server/pull/28

Execute 
```
npm install
npm run bootstrap
npm run compile
node examples/auditLogging/server.js
```

This will start the audit logging example where some audit logs are written to stdout with every request.

#### 2. JS SDK

Gotta build and link the JS SDK.

Get this PR (https://github.com/aerogear/aerogear-js-sdk/pull/195)

Execute
```
npm install
npm run bootstrap
npm run build
npm run link
# npm link fucks up some stuff. gotta run bootstrap again
npm run bootstrap 
```

#### 3. Sample app

Get https://github.com/aliok/sync-ionic-example-auditing
Edit `src/app/tab1/tab1.page.ts` and change the ip with your local ip.
```
const uri = 'http://192.168.1.111:4000/graphql';
```

Execute
```
npm link @aerogear/datasync-js
ionic build

# in my machine ionic cordova run android doesn't work. so I do it manually
ionic cordova build android
adb install platforms/android/app/build/outputs/apk/debug/app-debug.apk
```

#### 4. Final steps

When the Cordova app starts, you will see a button called "Voyager" at the top.
Click on that one.
That button will initiate a Graphql request. And in this sample app, auditLogging=true is passed to JS SDK.

You will see some logs in stdout in Voyager server similar to this one (important part is the `clientInfo` field):
```json
{
  "level": 30,
  "time": 1545385687476,
  "pid": 11889,
  "hostname": "localhost.localdomain",
  "tag": "AUDIT",
  "msg": "",
  "operationType": "query",
  "fieldName": "hello",
  "parentTypeName": "Query",
  "path": "hello",
  "success": true,
  "arguments": {},
  "clientInfo": {
    "clientId": "848d2a10-0505-11e9-888f-8d166149101a",
    "timestamp": 1545385686843,
    "data": {
      "app": {
        "appId": "io.ionic.starter",
        "appVersion": "0.0.1",
        "sdkVersion": "2.0.0",
        "framework": "cordova"
      },
      "device": {
        "platform": "android",
        "platformVersion": "9",
        "device": "Android SDK built for x86_64"
      }
    }
  },
  "v": 1
}
```

### CODE REVIEW

**Comment by aliok** [comment]
Ready for code review and verification guys.

@danielpassos @wtrocki @darahayes

**Comment by danielpassos** [comment]
Just wondering if we should add a default value for `auditLogging` in `SyncConfig`

**Comment by aliok** [comment]
> Just wondering if we should add a default value for auditLogging in SyncConfig

Sure, doing it now. Default false ;)

**Comment by danielpassos** [comment]
I got this warning but we can fix it later

```
```WARNING in Circular dependency detected:
../../Development/Projects/AeroGear/aerogear-js-sdk/packages/core/dist/Core.js -> ../../Development/Projects/AeroGear/aerogear-js-sdk/packages/core/dist/metrics/index.js -> ../../Development/Projects/AeroGear/aerogear-js-sdk/packages/core/dist/metrics/MetricsService.js -> ../../Development/Projects/AeroGear/aerogear-js-sdk/packages/core/dist/Core.js```
```

**Comment by danielpassos** [comment]
PS: We should add this on [apollo-voyager-ionic-example](https://github.com/aerogear/apollo-voyager-ionic-example)

**Comment by wtrocki** [comment]
PR was merged with core change that is not released and it's breaking backwards compatibility. 
We will need to release SDK soon.

**Comment by aliok** [comment]
> PR was merged with core change that is not released.
> We will need to release SDK soon.

Ok

**Pull request merged**
