### PR TITLE
chore: update release notes

### PR DESCRIPTION
**Pull request by darahayes**
### Description

@wtrocki @StephenCoady I've added an **Unreleased** section following a format/standard called [Keep a Changelog](https://keepachangelog.com/en/0.3.0/)

When we go to cut a release we simply rename the unreleased heading to the new version and start a new unreleased section. Let me know what you think.

##### Checklist

- [x] `npm test` passes
- [x] `npm run build` works
- [x] tests are included
- [x] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
Like the changes but we will need to apply this to entire 2.6 before merge.

**Comment by wtrocki** [comment]
@darahayes Can you reformat this notes as we doing release now?

**Comment by wtrocki** [comment]
We can use different format from upcomming release

**Comment by darahayes** [comment]
@wtrocki sure. I'll follow the same format you guys are using for 0.7.0 right?

**Comment by wtrocki** [comment]
Yes. We so we might reformat it or join both. I do not mind but we need that to be put release notes with 2.6.0

**Pull request merged**
