### PR TITLE
chore: added script to make development easier

### PR DESCRIPTION
**Pull request by StephenCoady**
### Description

added a small script to the base of the sdk to make developing and testing the sdk much easier.

NOTE: it assumes offix is in the same directory as the aerogear-sdk

##### Checklist

- [ ] `npm test` passes
- [ ] `npm run build` works
- [ ] tests are included
- [ ] documentation is changed or added

### CODE REVIEW

**Comment by wtrocki** [comment]
Awesome work!

**Comment by darahayes** [comment]
Really nice PR, a small suggestion would be to document the fact that it exists and what it does somewhere. Perhaps the Readme?

**Comment by wtrocki** [comment]
I guess the same will happen for the voyager-server?

**Comment by wtrocki** [comment]
For actual linking problem.
I actually started to hack cordova by specifying `alias npm=yarn` and it does the job as install command is the same, but this works only when we link things using yarn rather than NPM. Yarn links are better

**Comment by wtrocki** [comment]
@StephenCoady I will be happy to merge this and we can experiment with alias on yarn on our own. I alised that globally and going to see if I will see any issues.

**Comment by wtrocki** [comment]
@jhellar Do you think we can have some label that circleCI will read to skip master release. There will be actually tones of changes that are not code ones and we can save a lots of traffic and time if we skip the steps.

**Pull request merged**
