### PR TITLE
Aerogear 8447 2

### PR DESCRIPTION
**Pull request by StephenCoady**
replica of [this PR](https://github.com/aerogear/aerogear-js-sdk/pull/237) by @jhellar 

pushing here to preserve his fork.

@wtrocki can you take a look and tell me if the link flow still looks correct, had to do a small bit of refactoring

### Description

This is implemented with custom `RetryLink` [1]. It has a queue for all incoming operations. When there is a new operation, it will try to forward it. On network error it will schedule next try. If there is operation with response from server, all operations in queue are force retried.

When creating `RetryLink` user can provide `shouldRetry` function to cancel retry if needed.

[1] https://github.com/aerogear/aerogear-js-sdk/pull/237/files#diff-46acc41354166331ff353344d6065e85

##### Checklist

- [x] added retryLink
- [x] unit tests
- [ ] ~~integration tests~~
- [ ] documentation

Integration tests moved to separate jira - https://issues.jboss.org/browse/AEROGEAR-8521

### CODE REVIEW

**Comment by wtrocki** [comment]
Going to verify this. Check integration tests etc. still some work needed.

**Comment by wtrocki** [comment]
Pushed final version. Released all under: @aerogear/voyager-client@2.1.0-dev.8

**Comment by wtrocki** [comment]
Ok. Maybe to reduce impact and force users to go with retry handler we could just allow users to pass retryFunction. If no retry function is passed then retry link will be disabled. 
This will be much cleaner aproach. 

@psturc @StephenCoady @danielpassos

**Comment by StephenCoady** [comment]
@wtrocki +1 on that approach. covers us from worrying about things like infinite loops too

**Comment by wtrocki** [comment]
😆

**Comment by wtrocki** [comment]
Great work @jhellar! Really good to have this in the project and available to community!

**Pull request merged**
