### PR TITLE
Remove customLinkBuilder

### PR DESCRIPTION
**Pull request by jhellar**
### Description

https://issues.jboss.org/browse/AEROGEAR-8452

Links like offlineQueueLink or conflictLink should be exposed, so that users can build their own link chains. For example user may want to add retry link before http link. It should be documented how to build custom chains.

### CODE REVIEW

**Comment by wtrocki** [comment]
@jhellar They will be eventually in separate packages. THen entire client will be really thin.
I was proponent to remove fact that people can supply their custom link as this may not be as usable

**Comment by jhellar** [comment]
@wtrocki ok. Other reason I created this PR is this https://github.com/aerogear/aerogear-js-sdk/blob/master/packages/sync/src/links/LinksBuilder.ts#L13

I think it would be better not to pass the `offlineQueueLink` like this. Would it make sense to remove the `readme` and `expose` parts from this PR and leave just the restructuring, so that `offlineQueueLink` is accessible in `createClient` where it is then used?

**Comment by wtrocki** [comment]
I would say entire thing is not needed. We should remove https://github.com/aerogear/aerogear-js-sdk/blob/master/packages/sync/src/links/LinksBuilder.ts#L18 
Remove this from config and docs and then do everything including restore handler together. 
This will give better flexibility and remove amount of hacks. 

If someone wants to go custom they will just copy or extend this as there is no other implementation.

**Comment by jhellar** [comment]
@wtrocki ok, should be fixed now

**Comment by jhellar** [comment]
@wtrocki the definitions should be exposed now

**Pull request merged**
