### PR TITLE
AEROGEAR-2677 - add device lock security check

### PR DESCRIPTION
**Pull request by rachael-oregan**
## Motivation

JIRA: https://issues.jboss.org/browse/AEROGEAR-2677

## Description
Added security check to check if the device lock is set or not.

### CODE REVIEW

**Comment by rachael-oregan** [comment]
@wtrocki or @aidenkeating would one of ye be able to verify these checks on an iOS device? I tried the emulator but its not loading the menu for me still

**Comment by aidenkeating** [comment]
@rachael-oregan I had the same issue. I will try to verify now

**Comment by wtrocki** [comment]
@rachael-oregan Just seen it. Sorry

**Comment by aidenkeating** [comment]
This does not seem to be working on a device, I think @rachael-oregan is ill today. I will make the appropriate changes and create a PR with the fixes.

**Comment by aidenkeating** [comment]
Closed for #91

**Pull request closed without merging**
