### PR TITLE
Added integration tests for DataSync

### PR DESCRIPTION
**Pull request by jhellar**
## Motivation
https://issues.jboss.org/browse/AEROGEAR-8111

## What
- added integration tests for offline mutations

## How
Tests implemented with Karma.

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] Changes have been successfully verified by another team member

### CODE REVIEW

**Comment by wtrocki** [comment]
@jhellar This looks uber awesome. I would love to get more deeper into the implementation details sometime next week.

Side question: Are you planning to address those TODO's in this PR's? 

I actually started to see that js-sdk becomes too restrictive to sync itself - we may revisit where it should land. Ideally this tests should be in the same repo as server and client. Maybe this could mean merging client and the server? 

ping @darahayes

**Comment by wtrocki** [comment]
It looks like @noSquash/@onlineOnly operations always failing here. We may need to see if this is a bug (probably is)

ping @darahayes @StephenCoady

**Comment by StephenCoady** [comment]
@wtrocki @jhellar I will take a look

**Comment by StephenCoady** [comment]
update: the directive is making it to the server for some reason and is not being stripped from the request. still investigating.

**Comment by jhellar** [comment]
@StephenCoady @wtrocki it should be ready for review.

**Comment by wtrocki** [comment]
@StephenCoady My guess will be to log bug and prioritize them so they will land into the next milestone (aka sprint)

**Comment by wtrocki** [comment]
@jhellar I'm very happy with the changes. Let's merge this with this 2 cases disabled for the moment (we will add info to ticket to enabled them again.

**Pull request merged**
