### PR TITLE
[WIP] feat: auth integration tests

### PR DESCRIPTION
**Pull request by jhellar**
### Description

https://issues.jboss.org/browse/AEROGEAR-9146

### CODE REVIEW

**Comment by wtrocki** [comment]
@jhellar CircleCi allows this ORB's to modularize builds. Maybe we can have actual logic for integration in this repository and execute this here. 
Apart from that this looks sooo nice.

**Comment by wtrocki** [comment]
@jhellar How this was build for PR? It should be building things on tag only right ?

**Comment by jhellar** [comment]
@wtrocki looking at the config.yml, publishing code and testing in browserstack could be modularized with ORBs. Will send a commit for it.

For the tag only, that is only for real npm publishing, right?

**Comment by wtrocki** [comment]
I meant that it looks like this code executes for PRs. Is that right ? Fine to approve this once we clear it

**Comment by wei-lee** [comment]
@jhellar @wtrocki stupid question, what is `ORB`?

**Comment by wei-lee** [comment]
@jhellar how long the tests will take?

**Comment by wtrocki** [comment]
The integration adds ~8 minutes to build time. (see build options below).
It is acceptable for PR's but it looks like it is configured for tags only now

**Comment by jhellar** [comment]
@wei-lee docs for the ORBs https://circleci.com/orbs/ I understand it that it is about config reusing

**Comment by jhellar** [comment]
@wtrocki I think that the circleci config `filters, tags, only, /.*/` is confusing - if I understand it right, it just says that any tag should trigger the build. The way to disable builds for PRs is with `branches, ignore` - https://github.com/aerogear/aerogear-js-sdk/pull/345/files#diff-1d37e48f9ceff6d8030570cd36286a61R161

**Comment by wtrocki** [comment]
My private preference will be to not run this for PR's as we do a lot of nonauth related tests and 8 minutes overhead is too much. +100 for prerelease builds!

**Comment by wei-lee** [comment]
@wtrocki @jhellar yeah, that would be my preference as well. Given that the integration tests will test a few services rather than just one, maybe we can run it as part of a release pipeline instead. We can chat about it a bit more.

**Comment by jhellar** [comment]
https://issues.jboss.org/browse/AEROGEAR-9270 -> closing this PR.

**Pull request closed without merging**
